import type { Metadata } from 'next';
import 'antd/dist/reset.css';
import './globals.css';
import { pretendard } from '@/styles/fonts';
import AntdRegistry from '@/lib/antd-registry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body className="overflow-x-hidden relative">
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
